### ISSUE TITLE
Not working in 17.2.0.46

### ISSUE THREAD

**Issue by helderfc** [syncfusion/essential-ui-kit-for-xamarin.forms#5]
The demo does not work if we update the nuget packages for the latest syncfusion version 17.2.0.46 or 17.2.0.47.

I think the problem is in SFlistview, in a personal project, I have the same problem in sflistview if I upgrade it. After 17.2.0.40.

Thank you

**Comment by SubburajPandianV** [comment]
Hi Helderfc, 
 
Sorry for the inconvenience caused.

We suspect that you’re facing issue with Android, the mentioned issue occurs because of Xamarin.Forms dependency update in our SfListView control, we have upgraded Xamarin.Forms dependency version of SfListView to 3.6.0.344457 in our 17.2.0.46 version (2019 Volume 2 – SP1 release). For using this Syncfusion update or later versions, you must have to upgrade Xamarin.Forms dependency in your project to Xamarin.Forms 3.6.0.344457 or higher and also needs to set the Android project target version as 9.0 to resolve this issue.  

We have mentioned the same as breaking changes in our release notes, 

https://help.syncfusion.com/xamarin/release-notes/v17.2.0.46?type=all#common-breaking-changes

Please find the documentation regarding target framework version,
  
https://help.syncfusion.com/xamarin/installation-and-upgrade/system-requirements#target-framework-compile-sdk-version-for-android  

Could you please check with these mentioned changes in your application and confirm whether the issue resolved at your end? If not, please let us know with the exact scenario, we will check and provide you the solution.

Regards,
Subburaj Pandian V

**Comment by MeikandaNayanar** [comment]
Hi Helderfc,
We hope the issue is resolved at your end with the above solution. If you still face the issue, please let us know the details, so that we can assist you further.
Please let us know if you need any clarifications in this.
Thanks,
Meikandan
