### ISSUE TITLE
Borderless Entry Multiline

### ISSUE THREAD

**Issue by luis-cortina** [syncfusion/essential-ui-kit-for-xamarin.forms#56]
Hi:

Any chance that you have designed an Entry with multiple lines and Word Wrap?

**Comment by YuvarajPalanisamy** [comment]
Hi Luis Cortina, 
 
Greetings from Syncfusion. 
 
We have analyzed your query and we have achieved your requirement “Entry with multiple lines and Word Wrap” by using our BorderlessEditor control instead of BorderlessEntry. Also, we have prepared the sample for your reference. Please find the sample from the below link. 
 
Sample: [https://www.syncfusion.com/downloads/support/directtrac/general/ze/SimpleLoginTemplate-703710644](https://www.syncfusion.com/downloads/support/directtrac/general/ze/SimpleLoginTemplate-703710644)  
  
For more information, 
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit.Android/Renderers/BorderlessEditorRenderer.cs  
 
Regards, 
Yuvaraj

**Comment by luis-cortina** [comment]
Thanks!!!
