### ISSUE TITLE
"requestLayout() improperly called by crc64ee486da937c010f4.LabelRenderer" error when expanding SfExpander

### ISSUE THREAD

**Issue by lynx-ralph** [syncfusion/essential-ui-kit-for-xamarin.forms#59]
Would like an update on this ongoing issue. 

I'm not sure why this was not being tracked here on github. 
Here's the latest thread that has not received an update on the fix since Oct 1st.

https://www.syncfusion.com/forums/150648/sfexpander-example

**Comment by LakshmiNatarajan21** [comment]
Hi @lynx-ralph ,

**#Regarding requestLayout() called improperly for LabelRenderer**

The reported issue in the framework level itself and we have logged the issue report to Xamarin team for the same,

**Bug report:** https://github.com/xamarin/XamarinCommunityToolkit/issues/573

Kindly refer to the above bug report for further updates. 

Meanwhile, this issue occurs due to the animation on Expander content. As of now, we suggest you to use the Expander without animation. Please find the following code snippets to overcome the issue,

```
<expander:SfExpander AnimationDuration="0" AnimationEasing="None">
    <expander:SfExpander.Header>
        <Grid Padding="10,0,0,0" HeightRequest="70">
            ...
        </Grid>
    </expander:SfExpander.Header>
    <expander:SfExpander.Content>
        <Grid HeightRequest="100" >
         ...
        </Grid>
    </expander:SfExpander.Content>
</expander:SfExpander>
```

**#Regarding requestLayout() improperly called by android.widget.TextView**

We regret to inform you that the reported issue occurs due to measuring the Expander icon with the same width. If we measure the Expander icon only when width and height differ then the Expander icon is not rendered in the use cases like loading the expander inside the ListView since, the ListView reuses the items we need to remeasure the expander. Hence, we suggest you to use the custom HeaderIcon to overcome the reported scenario.

Please refer to the following documentation to use custom icons in Expander from the following links,
**KB links:**
https://www.syncfusion.com/kb/11378/how-to-customize-header-icon-in-xamarin-forms-expander-sfexpander
https://www.syncfusion.com/kb/11469/how-to-use-a-custom-font-icon-for-expander-in-xamarin-forms-sfexpander
