### ISSUE TITLE
Can't compile in VS2019

### ISSUE THREAD

**Issue by redbinkieresearchlabs** [syncfusion/essential-ui-kit-for-xamarin.forms#61]
Using the VS XAML Templates. Added the login pages into the solution. The project is a xamarin.forms project. Get the following error when building:

LoginViewModel' does not contain a definition for 'NotifyPropertyChanged' and no accessible extension method 'NotifyPropertyChanged' accepting a first argument of type 'LoginViewModel' could be found (are you missing a using directive or an assembly reference?)

The same error shows on VS on my Windows laptop and Macbook.

**Comment by YuvarajPalanisamy** [comment]
Hi @redbinkieresearchlabs ,  
   
Greetings from Syncfusion.  
  
We have analyzed the reported problem and we would like to let you know that If the specified file [BaseViewModel.cs] already have in the application with the same name in the UIKit then, UIKit will ignore that file. In order to resolve that, need to add the required thing in your application.  
  
BaseViewModel.cs from UIKit is not added in the application. In that we have NotifyPropertyChanged event. Could you please use OnPropertyChanged instead of NotifyPropertyChanged to resolve this issue?  
   
Also please include LoginViewModel.cs in ViewModels/Forms folder due to the same class is having in ViewModels folder.  
    
Please find the github source file in the below  
   
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/ViewModels/Forms/LoginViewModel.cs  
   
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/ViewModels/BaseViewModel.cs  
   
For more information please refer the below UG link  
   
https://help.syncfusion.com/xamarin/uikit/gettingstarted  
 
Regards, 
Yuvaraj
