### ISSUE TITLE
license popup

### ISSUE THREAD

**Issue by omiddehghan2036** [syncfusion/essential-ui-kit-for-xamarin.forms#64]
Hello.
I Use this project but the pop-up license page is repeated in the app every time. How can i fix it ?

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi @omiddehghan2036,

We checked your query to avoid a license popup, need to have a license key for your Syncfusion account, and by registering that in the UIKit application, the popup will not be shown. 
 
Please find the below links to generate the license key for Syncfusion controls 
 
https://www.syncfusion.com/kb/8976/how-to-generate-license-key-for-essential-studio-products 
 
https://help.syncfusion.com/common/essential-studio/licensing/license-key?#how-to-generate-syncfusion-license-key 
 
How to register your license key in your application in order to avoid the licensing popup, please refer to the below links 
 
https://help.syncfusion.com/common/essential-studio/licensing/license-key?#how-to-register-the-syncfusion-license-key 
 
https://help.syncfusion.com/common/essential-studio/licensing/license-key?#how-to-generate-syncfusion-license-key 
 
Please refer to the below link to get the license without having Syncfusion account (trial) 
 
https://help.syncfusion.com/common/essential-studio/licensing/license-key?#nugetorg-users-without-a-syncfusion-account 
 
After addressing the suggestion on the links above, you are still facing the issue, please let us know. 
 
Regards,
Hemalatha M.

**Comment by SwingsetTheory** [comment]
This fixes it temporarily but the nag window returns every 30 days.

IMHO "nag-ware" is not the same as "free".

Right on the main GitHub page it says "Free and beautiful XAML template pages for Xamarin.Forms apps," and the word "free" is all over your promotional material.

This is false advertising if you ask me. 

A free product has no strings attached, but this one has a string is quite large and heavy.

**Comment by MeikandaNayanar** [comment]
Hi @SwingsetTheory ,

The Syncfusion community licenses do not expire. You will continue to receive support and updates for new versions. Please refer to the below documentation to know more about the Syncfsuion community license.

https://www.syncfusion.com/products/communitylicense 

Please let us know if you need any further assistance in this.

Thanks
Meikandan
