### ISSUE TITLE
UI is very beautiful, but there is no beautiful automatic update UI function. I'm looking forward to it

### ISSUE THREAD

**Issue by bobotan** [syncfusion/essential-ui-kit-for-xamarin.forms#69]

**Comment by YuvarajPalanisamy** [comment]
Hi,

Greetings from Syncfusion. 

Could you please explain your need with more information to check at our end since we are not clear about exact requirement? In our Syncfusion Essential Xamarin.Forms UIKit pages are pre-defined pages with valid template.

If possible, could you please share the web link related to your requirement which will be helpful to provide further assistance on this.

Regards,
Yuvaraj.
